# Site settings
title: chen
header-img: "img/green.jpg"
tagline: "cn"  
description: "陈超|chen'blog"  
baseurl: ""
url: "http://blog.cscumt.com"  

# About/contact
owner: 
  name: " cumt醋"
  email: 920658920@qq.com
  bio: "写就是写的报酬"

# Data
gavatar: http://blog.cscumt.com/Az..png
favicon: img/favicon.png

#douban_username:  cnfeat
#twitter_username: feat
github_username: cumt6868
#facebook_username: 
#weibo_username: cnfeat 
#zhihu_username: feat

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Xuzhou

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "chen"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : cumt醋
  disqus :
      short_name : cumt醋

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
