permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: 
cdn_url: 7u2t01.com1.z0.glb.clouddn.com
lsi: false
safe: true
timezone: Asia/Xuzhou
auto: false 

paginate: 8
paginate_path: "page:num"

kramdown:
  input: GFM
  

JB :
  IMAGE_PATH : http://blog.cscumt.com/images

# presonal config
domain: http://cscumt.com
title: chen's blog
author: 
email: 
github: cumt6868

config:
  js_dir:
  img_dir:
  css_dir:
